name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Download Allure History Artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-results-history
          path: allure-results-history
        continue-on-error: true

      - name: Run Cypress Tests
        run: npm run test

      - name: Generate Allure Report
        run: npm run allure:report

      - name: Save Allure History
        run: |
          echo "Saving Allure history..."
          mkdir -p allure-results-history
          cp -r allure-results/history allure-results-history

      - name: Upload Allure History Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-history
          path: allure-results-history

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: false
